### PR TITLE
Update marzban.sh

### PR DESCRIPTION
**Pull request by DigneZzZ**
fixed issue with yq

### CODE REVIEW

**Comment by DigneZzZ** [comment]
Adapted for Debian and Centos

**Comment by DigneZzZ** [comment]
done. Now it works.

**Comment by ImMohammad20000** [comment]
can you add autocomplete to script too?

**Comment by DigneZzZ** [comment]
> can you add autocomplete to script too?

autocomplete for which params?

**Comment by DigneZzZ** [comment]
> > > can you add autocomplete to script too?
> > 
> > 
> > autocomplete for which params?
> 
> install restart uninstall and others

i dont understand, What do you want to autocomplete?

**Comment by DigneZzZ** [comment]
### Backup Service and Backup Functionality

This PR introduces the **Backup Service** and **Backup Functionality** for the Marzban. The new features allow automated backups of critical data and database configurations to a specified directory and support scheduled backups with optional Telegram integration for backup delivery.

#### Key Features:
1. **Backup Functionality**:
   - Creates a compressed archive of essential files, directories, and database dumps.
   - Supports splitting archives over 49MB for Telegram file size restrictions.
   - Provides server details and backup time in the Telegram message.

2. **Backup Service**:
   - Configurable via a user-friendly interface.
   - Enables scheduling backups with a custom interval (1-24 hours).
   - Allows easy reconfiguration or removal of the service.
   - Integrates with Telegram for automated delivery of backup archives.

3. **Crontab Integration**:
   - Automatically schedules backup tasks in `crontab` with a unique marker for easy management.
   - Ensures robust task removal during service deactivation.

---

### Usage Instructions

#### 1. Configure the Backup Service:
Run the following command to initialize or configure the backup service:
```bash
marzban backup-service
```

- Enter your **Telegram Bot API Key** and **Chat ID**.
- Specify the interval for backups in hours (1-24).
- The backup service will be scheduled, and backups will be sent to Telegram.

#### 2. Remove the Backup Service:
To deactivate and remove the backup service:
```bash
marzban backup-service
```
- Select **"Remove Backup Service"** from the menu.

#### 3. Perform Manual Backups:
To manually create and send a backup, run:
```bash
marzban backup
```

---

### Example Telegram Message
```text
📦 Backup Information
🗂 Part: part_aa
🌐 Server IP: 192.168.1.100
📁 Included Files:
  - .env
  - docker-compose.yml
  - /var/lib/marzban (excluding xray-core, mysql)
⏰ Backup Time: Tue Dec 5 12:00:00 PM UTC 2024
```

**Comment by Joursoir** [comment]
@DigneZzZ great job! thank you for your effort :)

To make the review process much easier, it would be helpful if commit messages were more descriptive and named clearly. It would not be good to squash all this commit to one that do 2 separate things (maybe even more, idk)

From my side, I can confirm that this patch actually fixes the issue with `yq`.

**Comment by DigneZzZ** [comment]
> @DigneZzZ great job! thank you for your effort :)
> 
> 
> 
> To make the review process much easier, it would be helpful if commit messages were more descriptive and named clearly. It would not be good to squash all this commit to one that do 2 separate things (maybe even more, idk)
> 
> 
> 
> From my side, I can confirm that this patch actually fixes the issue with `yq`.

Yes, I agree with you, we discussed this with Ted as well :) That’s why we decided that the upcoming changes and fixes would be better combined into one, considering the frequency of PR approvals for merging.

**Pull request merged**
