### PR TITLE
Update marzban-node.sh

### PR DESCRIPTION
**Pull request by DigneZzZ**
Corrected the port handling
Added a check to ensure that when entering the second port, it verifies if the port has already been entered in the first.

image

### CODE REVIEW

**Comment by DigneZzZ** [comment]
Enhanced port range from 1 to 65535

**Comment by BehnamAB** [comment]
i cant add port 

Enter the SERVICE_PORT (default 62050): 1024
Port 1024 is already in use. Please enter another port.

in errro for more port

**Comment by BehnamAB** [comment]
Screenshot 2024-08-05 005625

**Comment by iamtheted** [comment]
@BehnamAB It'll be fixed soon, there's an open PR for this issue.

**Comment by DigneZzZ** [comment]
Set APP_NAME to NODE_NAME, or script name if NODE_NAME is not set

**Comment by iamtheted** [comment]
@SaintShit It's merge time bro. 🚀

**Comment by BehnamAB** [comment]
> Screenshot 2024-08-05 005625

Is this problem not solved?

**Comment by DigneZzZ** [comment]
> > Screenshot 2024-08-05 005625
> 
> Is this problem not solved?

The problem is solved in this PR, we are waiting for it to be merged.

**Comment by DigneZzZ** [comment]
There is no need to use another variable `NODE_NAME` if we **agreed** that the default value during installation should be set to `marzban-node`, but the user can still choose their own name using the `--name` option.

**Pull request merged**
