### PR TITLE
Node install script

### PR DESCRIPTION
**Pull request by DigneZzZ**
Added installation of marzban-node and container management function.
Added the option to choose REST protocol.
Updated help function with basic information output.
Certificate for the panel is added during the installation process.

### CODE REVIEW

**Comment by DigneZzZ** [comment]
**Before applying my merge, the repositories need to be adjusted.**

**Comment by Aknuun** [comment]
great 👍

**Comment by DigneZzZ** [comment]
Updated marzban.sh
**You can now choose the Marzban version before installation. Many thanks to @xmohammad1 **

**Comment by aminwork2023** [comment]
Amazing ❤️❤️

**Comment by iamtheted** [comment]
I appreciate your effort bro! 💙
Thanks a lot.

**Comment by Ashkan-Khademi** [comment]
Nice

**Comment by DigneZzZ** [comment]
Updated Work Logic:

* The default service name has been shortened to node (previously marzban-node).
* Added the ability to set a custom service name using the `--name node1` installation attribute.
exmpl: `@ install --name node1`
* Added the ability to specify the service port.
* Added the ability to specify the API port.
* Minor fixes.
* The `node help` command now reads ports from docker-compose.

**Comment by xmohammad1** [comment]
I appreciate your work

**Comment by iamtheted** [comment]
Hi again
I really love the change in CLI which can set different CLI commands for each directory.
Awesome work, bro. 💙

**Comment by SaintShit** [comment]
Thank you! this PR was very handy.

**Comment by SaintShit** [comment]
Have a question, you meant to have multiple script and nodes being installed by specifying --name variable?

**Comment by DigneZzZ** [comment]
> I have a question, you meant to have multiple script and nodes being installed by specifying --name variable?

@SaintShit The request was to allow specifying a custom name for the service and the installation folder, so that those who want to install multiple containers to work with multiple panels can use them separately.

**Pull request merged**
