### PR TITLE
Update marzban.sh

### PR DESCRIPTION
**Pull request by xmohammad1**
Users choose which version to install

### CODE REVIEW

**Comment by iamtheted** [comment]
Perfect! Thank you so much! 💙
I have been waiting for this for so long!

**Comment by amir3dmax** [comment]
nice plan

**Comment by neoshisystem** [comment]
Nice

**Comment by danialzsh** [comment]
awesome

**Comment by qirmizialma** [comment]
♥♥♥♥♥♥♥

**Comment by ali-pulad** [comment]
well done

**Pull request closed without merging**
