### PR TITLE
specific version on link marzban.sh

### PR DESCRIPTION
**Pull request by xmohammad1**
install latest or specific version depend on request

this is an example for installing a specific version
```
sudo bash -c "$(curl -sL https://raw.githubusercontent.com/xmohammad1/Marzban-scripts/patch-2/marzban.sh)" @ install v0.5.2

```
this is an example for installing latest version
```
sudo bash -c "$(curl -sL https://raw.githubusercontent.com/xmohammad1/Marzban-scripts/patch-2/marzban.sh)" @ install
```

### CODE REVIEW

**Comment by iamtheted** [comment]
Perfect! 💙
I have been waiting for this for so long!
Thank you so much!

**Comment by Mrclocks** [comment]
This is a really great feature , thanks mohammad ❤️

**Comment by Aknuun** [comment]
good

**Comment by MHMahdian** [comment]
Good 👍

**Comment by danialzsh** [comment]
do this 🫡

**Comment by neoshisystem** [comment]
عالی

**Pull request closed without merging**
